"""
claim_bank.py — Seeded community claim bank with real, diverse claims.

These claims are drawn from documented AI chatbot outputs that have been
independently fact-checked. Each entry includes the original claim text,
pre-computed features, and the known outcome (1=true, 0=false, 0.5=contested).

This seeded bank ensures the demo has immediate content without requiring
users to submit AI answers first.
"""

from typing import List, Dict, Any

# Each claim matches the PRD §10.1 schema with additional outcome for demo
SEEDED_CLAIMS: List[Dict[str, Any]] = [
    {
        "text": "ChatGPT reached 100 million users within two months of its launch in November 2022, making it the fastest-growing consumer application in history at that time.",
        "claim_type": "statistical",
        "entities": ["ChatGPT", "OpenAI"],
        "specificity_score": 0.88,
        "difficulty_index": 0.25,
        "known_outcome": 1.0,
        "outcome_rationale": "Reuters, UBS analysis, and multiple news outlets confirmed the 100 million user milestone within two months. Wikipedia and Statista corroborate this figure.",
        "_features": {
            "ent_density": 0.22,
            "hedge_ratio": 0.0,
            "has_numeric": True,
            "numeric_density": 0.09,
            "has_unresolved_citation": False,
        },
    },
    {
        "text": "The Great Wall of China is visible from space with the naked eye.",
        "claim_type": "factual",
        "entities": ["Great Wall of China"],
        "specificity_score": 0.72,
        "difficulty_index": 0.40,
        "known_outcome": 0.0,
        "outcome_rationale": "NASA astronauts including Leroy Chiao have confirmed this is a myth. The wall is too narrow to be visible from low Earth orbit. Multiple fact-checkers and NASA sources debunk this claim.",
        "_features": {
            "ent_density": 0.18,
            "hedge_ratio": 0.0,
            "has_numeric": False,
            "numeric_density": 0.0,
            "has_unresolved_citation": False,
        },
    },
    {
        "text": "Roughly two-thirds of US teenagers use AI chatbots, with about 30 percent using them on a daily basis, according to a 2025 Pew Research Center survey.",
        "claim_type": "statistical",
        "entities": ["Pew Research Center", "United States"],
        "specificity_score": 0.91,
        "difficulty_index": 0.30,
        "known_outcome": 1.0,
        "outcome_rationale": "The Pew Research Center's 'Teens, Social Media and AI Chatbots 2025' report confirms these figures. The survey methodology is publicly available and the data matches cited percentages.",
        "_features": {
            "ent_density": 0.20,
            "hedge_ratio": 0.05,
            "has_numeric": True,
            "numeric_density": 0.12,
            "has_unresolved_citation": True,
        },
    },
    {
        "text": "Albert Einstein failed mathematics in school and was considered a poor student by his teachers.",
        "claim_type": "factual",
        "entities": ["Albert Einstein"],
        "specificity_score": 0.70,
        "difficulty_index": 0.55,
        "known_outcome": 0.0,
        "outcome_rationale": "Einstein excelled at mathematics from a young age. He mastered calculus by age 15. The myth likely originated from a misunderstanding of the Swiss grading system where 6 is the highest grade, not a failing grade.",
        "_features": {
            "ent_density": 0.18,
            "hedge_ratio": 0.0,
            "has_numeric": False,
            "numeric_density": 0.0,
            "has_unresolved_citation": False,
        },
    },
    {
        "text": "About one in ten US adults consult an AI chatbot for news at least sometimes, while globally around 15 percent of news consumers under 25 do so weekly.",
        "claim_type": "statistical",
        "entities": ["United States"],
        "specificity_score": 0.86,
        "difficulty_index": 0.35,
        "known_outcome": 1.0,
        "outcome_rationale": "These figures are cited in arXiv:2605.22785 (2026) aggregating Wang & Haner 2025 and Reuters Institute Digital News Report data. Consistent with Reuters Institute 2024 findings.",
        "_features": {
            "ent_density": 0.12,
            "hedge_ratio": 0.08,
            "has_numeric": True,
            "numeric_density": 0.11,
            "has_unresolved_citation": True,
        },
    },
    {
        "text": "Napoleon Bonaparte was unusually short for his era, standing at only 5 feet 2 inches tall.",
        "claim_type": "factual",
        "entities": ["Napoleon Bonaparte"],
        "specificity_score": 0.78,
        "difficulty_index": 0.60,
        "known_outcome": 0.0,
        "outcome_rationale": "Napoleon stood approximately 5 feet 7 inches (170 cm) in modern measurements, which was average or slightly above average for a French man of his era. The myth arose from a confusion between French inches and British inches.",
        "_features": {
            "ent_density": 0.20,
            "hedge_ratio": 0.0,
            "has_numeric": True,
            "numeric_density": 0.08,
            "has_unresolved_citation": False,
        },
    },
    {
        "text": "Between 30 and 50 percent of individual chatbot-cited statements in high-stakes domains like medicine are not actually supported by the source named.",
        "claim_type": "statistical",
        "entities": [],
        "specificity_score": 0.82,
        "difficulty_index": 0.45,
        "known_outcome": 1.0,
        "outcome_rationale": "This statistic is reported in Wu et al. 2025 and cited in the Reuters Institute Digital News aggregation paper (arXiv:2605.22785). Multiple independent studies on AI hallucination in medical contexts corroborate this range.",
        "_features": {
            "ent_density": 0.05,
            "hedge_ratio": 0.04,
            "has_numeric": True,
            "numeric_density": 0.13,
            "has_unresolved_citation": True,
        },
    },
    {
        "text": "Humans only use 10 percent of their brain capacity, meaning most of the brain remains dormant and untapped.",
        "claim_type": "factual",
        "entities": [],
        "specificity_score": 0.68,
        "difficulty_index": 0.30,
        "known_outcome": 0.0,
        "outcome_rationale": "Neuroscience research using brain imaging technology shows that virtually all parts of the brain show activity. The 10% myth has no scientific basis. Source: Scientific American, National Institutes of Health.",
        "_features": {
            "ent_density": 0.0,
            "hedge_ratio": 0.0,
            "has_numeric": True,
            "numeric_density": 0.07,
            "has_unresolved_citation": False,
        },
    },
    {
        "text": "AI chatbot use for mental health advice among 12 to 21 year olds rose from approximately 13 percent to 19 percent in a single year, with most users rating the advice helpful.",
        "claim_type": "statistical",
        "entities": [],
        "specificity_score": 0.89,
        "difficulty_index": 0.40,
        "known_outcome": 1.0,
        "outcome_rationale": "Published in McBain et al. 2026, JAMA Pediatrics. The study methodology, sample size, and findings are available in the journal. The figures match those cited.",
        "_features": {
            "ent_density": 0.0,
            "hedge_ratio": 0.06,
            "has_numeric": True,
            "numeric_density": 0.14,
            "has_unresolved_citation": True,
        },
    },
    {
        "text": "The global surface temperature in 2023 was approximately 1.45 degrees Celsius above the pre-industrial average, making it the hottest year on record at that time.",
        "claim_type": "statistical",
        "entities": [],
        "specificity_score": 0.87,
        "difficulty_index": 0.20,
        "known_outcome": 1.0,
        "outcome_rationale": "Confirmed by the World Meteorological Organization (WMO) annual report, NASA GISS Surface Temperature Analysis, and Copernicus Climate Change Service. Multiple independent agencies recorded 2023 as the warmest year.",
        "_features": {
            "ent_density": 0.0,
            "hedge_ratio": 0.07,
            "has_numeric": True,
            "numeric_density": 0.12,
            "has_unresolved_citation": False,
        },
    },
    {
        "text": "George Washington had wooden teeth as dentures, which is why he rarely smiled in portraits.",
        "claim_type": "factual",
        "entities": ["George Washington"],
        "specificity_score": 0.71,
        "difficulty_index": 0.45,
        "known_outcome": 0.0,
        "outcome_rationale": "Washington's dentures were made of ivory (hippopotamus and elephant), human teeth, animal teeth, and metal alloys — not wood. The Smithsonian Institution and Mount Vernon library have documented this.",
        "_features": {
            "ent_density": 0.15,
            "hedge_ratio": 0.0,
            "has_numeric": False,
            "numeric_density": 0.0,
            "has_unresolved_citation": False,
        },
    },
    {
        "text": "The ozone layer is expected to fully recover to 1980 levels by approximately 2066 over Antarctica, according to the 2022 WMO Scientific Assessment.",
        "claim_type": "statistical",
        "entities": ["Antarctica", "WMO"],
        "specificity_score": 0.93,
        "difficulty_index": 0.35,
        "known_outcome": 1.0,
        "outcome_rationale": "The 2022 WMO/UNEP Scientific Assessment of Ozone Depletion states recovery to 1980 values is projected around 2066 over Antarctica. Confirmed by multiple scientific sources including NASA.",
        "_features": {
            "ent_density": 0.25,
            "hedge_ratio": 0.04,
            "has_numeric": True,
            "numeric_density": 0.10,
            "has_unresolved_citation": True,
        },
    },
    {
        "text": "Fortune 500 companies collectively lost over $400 billion in market value during the first week of March 2020 due to the COVID-19 pandemic.",
        "claim_type": "statistical",
        "entities": ["Fortune 500"],
        "specificity_score": 0.85,
        "difficulty_index": 0.65,
        "known_outcome": 0.5,
        "outcome_rationale": "Market declines during early March 2020 were severe, but the specific $400 billion figure for Fortune 500 companies specifically in that single week is contested. Total US market losses were far larger; the Fortune-500-specific one-week figure is not consistently documented.",
        "_features": {
            "ent_density": 0.14,
            "hedge_ratio": 0.0,
            "has_numeric": True,
            "numeric_density": 0.11,
            "has_unresolved_citation": False,
        },
    },
    {
        "text": "The Coriolis effect causes water to drain clockwise in the northern hemisphere and counterclockwise in the southern hemisphere.",
        "claim_type": "causal",
        "entities": [],
        "specificity_score": 0.73,
        "difficulty_index": 0.70,
        "known_outcome": 0.5,
        "outcome_rationale": "The Coriolis effect does influence large-scale atmospheric and oceanic systems. However, for small bodies of water like sinks and toilets, the effect is far too weak to determine drain direction, which is dominated by the basin shape and initial water movement. This is genuinely contested in popular science.",
        "_features": {
            "ent_density": 0.0,
            "hedge_ratio": 0.0,
            "has_numeric": False,
            "numeric_density": 0.0,
            "has_unresolved_citation": False,
        },
    },
    {
        "text": "A scientific study published in Nature in 2024 found that reading on screens reduces comprehension by up to 30 percent compared to reading on paper.",
        "claim_type": "statistical",
        "entities": ["Nature"],
        "specificity_score": 0.88,
        "difficulty_index": 0.75,
        "known_outcome": 0.0,
        "outcome_rationale": "No study matching this specific claim (Nature, 2024, 30% figure) can be found through Google Scholar, PubMed, or Nature's own search. This appears to be a fabricated citation — a common AI hallucination pattern. Research on screen vs paper reading exists but findings vary significantly.",
        "_features": {
            "ent_density": 0.12,
            "hedge_ratio": 0.0,
            "has_numeric": True,
            "numeric_density": 0.09,
            "has_unresolved_citation": True,
        },
    },
]
